# Generated by Django 4.1 on 2022-11-03 08:29

from django.db import migrations, models
import django.db.models.manager


class Migration(migrations.Migration):

    dependencies = [
        ('book', '0001_initial'),
    ]

    operations = [
        migrations.AlterModelManagers(
            name='books',
            managers=[
                ('myObjects', django.db.models.manager.Manager()),
            ],
        ),
        migrations.AddField(
            model_name='books',
            name='is_deleted',
            field=models.CharField(default='n', max_length=2),
        ),
    ]
