# Generated by Django 4.1 on 2022-11-23 13:01

from django.db import migrations, models
import django.db.models.manager


class Migration(migrations.Migration):

    dependencies = [
        ('book', '0002_alter_books_managers_books_is_deleted'),
    ]

    operations = [
        migrations.CreateModel(
            name='Contact',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('username', models.CharField(max_length=30)),
                ('email', models.EmailField(max_length=50)),
                ('phone', models.CharField(max_length=13)),
                ('desc', models.TextField()),
            ],
            managers=[
                ('myObjects', django.db.models.manager.Manager()),
            ],
        ),
        migrations.AlterModelManagers(
            name='books',
            managers=[
            ],
        ),
    ]
